sudo: false
language: c
cache:
  directories:
    - $HOME/.stack

# Handle submodules manually, since we have to clone from https urls instead of git urls
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/8.0.2/bin:$PATH

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - binutils-multiarch
      - ghc-8.0.2


matrix:
  include:
    - env: TEST_ARCH=tablegen
    - env: TEST_ARCH=ppc
    - env: TEST_ARCH=arm

script:
  - travis_wait ./scripts/test.sh $TEST_ARCH
