flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- dismantle-tablegen/
- dismantle-ppc/
extra-deps:
- QuickCheck-2.9.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1
- base-compat-0.9.3
- case-insensitive-1.2.0.7
- clock-0.7.2
- directory-1.3.1.1
- exceptions-0.8.3
- filemanip-0.3.6.3
- hashable-1.2.4.0
- located-base-0.1.1.0
- megaparsec-5.0.1
- mtl-2.2.1
- optparse-applicative-0.13.2.0
- parsec-3.1.11
- pretty-1.1.3.5
- primitive-0.6.1.0
- process-1.6.0.0
- random-1.1
- regex-1.0.0.0
- regex-base-0.93.2
- regex-tdfa-1.2.2
- regex-tdfa-text-1.0.0.3
- scientific-0.3.4.9
- split-0.2.3.1
- stm-2.4.4.1
- tagged-0.8.5
- tasty-0.11.0.4
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- template-haskell-2.11.1.0
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.3
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unix-compat-0.4.3.1
- unordered-containers-0.2.8.0
- vector-0.11.0.0
- zlib-0.6.1.2
resolver: ghc-8.0.2
