flags: {}
extra-package-dbs: []
packages:
- dismantle-tablegen/
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- exceptions-0.8.3
- hashable-1.2.4.0
- megaparsec-5.0.1
- mtl-2.2.1
- optparse-applicative-0.13.0.0
- primitive-0.6.1.0
- scientific-0.3.4.9
- stm-2.4.4.1
- text-1.2.2.1
- transformers-compat-0.5.1.4
- vector-0.11.0.0
resolver: ghc-8.0.1
