flags: {}
extra-package-dbs: []
packages:
- dismantle-tablegen/
- dismantle-ppc/
extra-deps:
- filemanip-0.3.6.3
- unix-compat-0.4.3.1
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- exceptions-0.8.3
- hashable-1.2.4.0
- megaparsec-5.0.1
- mtl-2.2.1
- optparse-applicative-0.13.0.0
- primitive-0.6.1.0
- scientific-0.3.4.9
- stm-2.4.4.1
- text-1.2.2.1
- transformers-compat-0.5.1.4
- vector-0.11.0.0
- tasty-0.11.0.4
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- QuickCheck-2.9.2
- dlist-0.8.0.2
- random-1.1
- tf-random-0.5
- async-2.1.1
- clock-0.7.2
- regex-tdfa-1.2.2
- tagged-0.8.5
- unbounded-delays-0.1.0.9
- parsec-3.1.11
- regex-base-0.93.2
- old-locale-1.0.0.7
- old-time-1.1.0.3
- polyparse-1.12
- located-base-0.1.1.0
- split-0.2.3.1
- case-insensitive-1.2.0.7
- zlib-0.6.1.2
resolver: ghc-8.0.2
