cabal-version:       3.0
name:                dismantle-arm
version:             0.1.0.0
synopsis:            A disassembler and assembler for ARM
license:             BSD-3-Clause
license-file:        LICENSE
author:              Jonathan Daugherty
maintainer:          jtd@galois.com
copyright:           2017 Jonathan Daugherty, Tristan Ravitch
category:            Development
build-type:          Simple
extra-source-files:  ChangeLog.md, data/ARM.tgen

common deps
  build-depends:       base >= 4.8 && < 5,
                       template-haskell,
                       parameterized-utils >= 1 && < 2.4,
                       dismantle-tablegen,
                       bytestring,
                       binary,
                       containers,
                       pretty,
                       split
  default-language:    Haskell2010

library opcodes
  import: deps
  visibility: public
  exposed-modules: Dismantle.ARM.ISA
                 , Dismantle.ARM.Opcodes
                 , Dismantle.ARM.Operands
  hs-source-dirs: src/opcodes

library disassembler
  import: deps
  visibility: public
  exposed-modules: Dismantle.ARM.Disassembler
  build-depends: dismantle-arm:opcodes
  hs-source-dirs: src/disassembler

library assembler
  import: deps
  visibility: public
  exposed-modules: Dismantle.ARM.Assembler
  build-depends: dismantle-arm:opcodes
  hs-source-dirs: src/assembler

library prettyprinter
  import: deps
  visibility: public
  exposed-modules: Dismantle.ARM.PrettyPrint
  build-depends: dismantle-arm:opcodes
  hs-source-dirs: src/prettyprinter

library testing
  import: deps
  visibility: public
  exposed-modules: Dismantle.ARM.Random
  build-depends: dismantle-arm:opcodes
  hs-source-dirs: src/testing

test-suite dismantle-arm-tests
  default-language: Haskell2010
  type: exitcode-stdio-1.0
  ghc-options: -Wall
  hs-source-dirs: tests
  main-is: Main.hs
  other-modules: MiscARMTests
  build-depends: base,
                 dismantle-tablegen,
                 dismantle-arm:opcodes,
                 dismantle-arm:disassembler,
                 dismantle-arm:assembler,
                 dismantle-arm:prettyprinter,
                 tasty,
                 tasty-hunit,
                 pretty,
                 text
