cabal-version:       3.0
name:                dismantle-ppc
version:             0.1.0.0
synopsis:            A disassembler and assembler for PPC
license:             BSD-3-Clause
license-file:        LICENSE
author:              Tristan Ravitch
maintainer:          tristan@nochair.net
copyright:           2016-2017 Tristan Ravitch
category:            Development
build-type:          Simple
extra-source-files:  ChangeLog.md, data/PPC.tgen, data/override/*.tgen

common deps
  build-depends:       base >= 4.8 && < 5,
                       template-haskell,
                       parameterized-utils >= 1 && < 2.2,
                       dismantle-tablegen,
                       bytestring,
                       binary,
                       pretty
  default-language:    Haskell2010

library opcodes
  import: deps
  visibility: public
  exposed-modules: Dismantle.PPC.ISA
                 , Dismantle.PPC.Opcodes
                 , Dismantle.PPC.Operands
  hs-source-dirs: src/opcodes

library disassembler
  import: deps
  visibility: public
  exposed-modules: Dismantle.PPC.Disassembler
  build-depends: dismantle-ppc:opcodes
  hs-source-dirs: src/disassembler

library assembler
  import: deps
  visibility: public
  exposed-modules: Dismantle.PPC.Assembler
  build-depends: dismantle-ppc:opcodes
  hs-source-dirs: src/assembler

library prettyprinter
  import: deps
  visibility: public
  exposed-modules: Dismantle.PPC.PrettyPrint
  build-depends: dismantle-ppc:opcodes
  hs-source-dirs: src/prettyprinter

library testing
  import: deps
  visibility: public
  exposed-modules: Dismantle.PPC.Random
  build-depends: dismantle-ppc:opcodes
  hs-source-dirs: src/testing

test-suite dismantle-ppc-tests
  default-language: Haskell2010
  type: exitcode-stdio-1.0
  ghc-options: -Wall
  hs-source-dirs: tests
  main-is: Main.hs
  build-depends: base,
                 dismantle-tablegen,
                 dismantle-ppc:opcodes,
                 dismantle-ppc:disassembler,
                 dismantle-ppc:assembler,
                 dismantle-ppc:prettyprinter,
                 tasty,
                 text
