{-# LANGUAGE TemplateHaskell #-}
module Dismantle.AArch64.ISA (
  isa
  ) where

import qualified Data.Binary.Get as B
import qualified Data.Binary.Put as B
import qualified Data.ByteString.Lazy as LBS
import qualified Data.List as L
import qualified Data.Set as S
import Data.Word ( Word8, Word16, Word32, Word64 )

import Language.Haskell.TH
import Language.Haskell.TH.Syntax

import Dismantle.Tablegen.ISA
import Dismantle.Tablegen.Types
import Dismantle.Tablegen.Parser.Types
  ( Metadata(Metadata)
  , defName
  , defMetadata
  )
import qualified Dismantle.AArch64.Operands as AArch64
import qualified Dismantle.ARM.ISA as ARM

asWord32 :: LBS.ByteString -> Word32
asWord32 = B.runGet B.getWord32be

fromWord32 :: Word32 -> LBS.ByteString
fromWord32 = B.runPut . B.putWord32be

isa :: ISA
isa = ISA { isaName = "AArch64"
          , isaTgenBitPreprocess = id
          , isaInputEndianness = Big
          , isaInstructionFilter = aarch64Filter
          , isaPseudoInstruction = aarch64Pseudo
          , isaOperandPayloadTypes = aarch64OperandPayloadTypes
          , isaInsnWordFromBytes = 'asWord32
          , isaInsnWordToBytes = 'fromWord32
          , isaInsnAssembleType = ''Word32
          , isaIgnoreOperand = const False
          , isaFormOverrides = overrides
          , isaMapOperandPayloadType = id
          , isaDefaultPrettyVariableValues = []
          , isaPrettyOverrides = []
          , isaUnusedBitsPolicy = Nothing
          }
  where

    word32Operand = OperandPayload { opTypeT = [t| Word32 |]
                                   , opConE = Nothing
                                   , opWordE = Nothing
                                   }

    aarch64OperandPayloadTypes =
        [ ("FPR128", AArch64.fPR128Operand)
        , ("FPR16", AArch64.fPR16Operand)
        , ("FPR32", AArch64.fPR32Operand)
        , ("FPR64", AArch64.fPR64Operand)
        , ("FPR8", AArch64.fPR8Operand)
        , ("GPR32", AArch64.gPR32Operand)
        , ("GPR64", AArch64.gPR64Operand)
        , ("GPR32sp", AArch64.gPR32spOperand)
        , ("GPR64sp", AArch64.gPR64spOperand)
        , ("GPR64sp0", AArch64.gPR64spOperand)
        , ("V128", AArch64.v128Operand)
        , ("WSeqPairClassOperand", AArch64.gPR32Operand)
        , ("XSeqPairClassOperand", AArch64.gPR64Operand)
        , ("Addsub_shifted_imm32", AArch64.addsubShiftedImm32Operand)
        , ("Addsub_shifted_imm64", AArch64.addsubShiftedImm64Operand)
        , ("Adrlabel", AArch64.adrlabelOperand)
        , ("Adrplabel", AArch64.adrplabelOperand)
        , ("Am_b_target", AArch64.amBTargetOperand)
        , ("Am_bl_target", AArch64.amBTargetOperand)
        , ("Am_brcond", AArch64.amBrcondOperand)
        , ("Am_tbrcond", AArch64.amTbrcondOperand)
        , ("Ccode", ARM.predOperand)
        , ("Am_ldrlit", AArch64.amLdrlitOperand)
        , ("Arith_extendlsl64", AArch64.arithExtendlsl64Operand)
        , ("Barrier_op", AArch64.barrierOpOperand)
        , ("Imm0_1", AArch64.imm01Operand)
        , ("Imm0_7", AArch64.imm07Operand)
        , ("Imm0_15", AArch64.imm015Operand)
        , ("Imm0_31", AArch64.imm031Operand)
        , ("Imm0_63", AArch64.imm063Operand)
        , ("Imm0_127", AArch64.imm0127Operand)
        , ("Imm0_65535", AArch64.imm065535Operand)
        , ("Imm32_0_15", AArch64.imm32015Operand)
        , ("Imm32_0_31", AArch64.imm32031Operand)
        , ("Logical_imm32", AArch64.logicalImm32Operand)
        , ("Logical_imm64", AArch64.logicalImm64Operand)
        , ("Movimm32_imm", AArch64.movimm32ImmOperand)
        , ("Movimm32_shift", AArch64.movimm32ShiftOperand)
        , ("Movimm64_shift", AArch64.movimm64ShiftOperand)
        , ("Mrs_sysreg_op", AArch64.mrsSysregOpOperand)
        , ("Msr_sysreg_op", AArch64.msrSysregOpOperand)
        , ("Prfop", AArch64.prfopOperand)
        , ("Pstatefield1_op", AArch64.pstatefield1OpOperand)
        , ("Pstatefield4_op", AArch64.pstatefield4OpOperand)
        , ("Ro_Wextend8", AArch64.roWextend8Operand)
        , ("Ro_Wextend16", AArch64.roWextend16Operand)
        , ("Ro_Wextend32", AArch64.roWextend32Operand)
        , ("Ro_Wextend64", AArch64.roWextend64Operand)
        , ("Ro_Wextend128", AArch64.roWextend128Operand)
        , ("Ro_Xextend8", AArch64.roXextend8Operand)
        , ("Ro_Xextend16", AArch64.roXextend16Operand)
        , ("Ro_Xextend32", AArch64.roXextend32Operand)
        , ("Ro_Xextend64", AArch64.roXextend64Operand)
        , ("Ro_Xextend128", AArch64.roXextend128Operand)
        , ("Simm7s4", AArch64.simm7s4Operand)
        , ("Simm7s8", AArch64.simm7s8Operand)
        , ("Simm7s16", AArch64.simm7s16Operand)
        , ("Simm9", AArch64.simm9Operand)
        , ("Sys_cr_op", AArch64.sysCrOpOperand)
        , ("Tbz_imm0_31_diag", AArch64.tbzImm031DiagOperand)
        , ("Tbz_imm32_63", AArch64.tbzImm3263Operand)
        , ("Uimm12s1", AArch64.uimm12s1Operand)
        , ("Uimm12s2", AArch64.uimm12s2Operand)
        , ("Uimm12s4", AArch64.uimm12s4Operand)
        , ("Uimm12s8", AArch64.uimm12s8Operand)
        , ("Uimm12s16", AArch64.uimm12s16Operand)
        , ("Addext", AArch64.addextOperand)
        , ("Addshift64", AArch64.addshift64Operand)
        , ("Unpredictable", word32Operand)
        , ("Fixedpoint_f32_i32", AArch64.fixedpointF32I32Operand)
        , ("Fixedpoint_f32_i64", AArch64.fixedpointF32I64Operand)
        , ("Fixedpoint_f16_i32", AArch64.fixedpointF16I32Operand)
        , ("Fixedpoint_f16_i64", AArch64.fixedpointF16I64Operand)
        , ("Fixedpoint_f64_i32", AArch64.fixedpointF64I32Operand)
        , ("Fixedpoint_f64_i64", AArch64.fixedpointF64I64Operand)
        , ("Fpimm16", AArch64.fpimm16Operand)
        , ("Fpimm32", AArch64.fpimm32Operand)
        , ("Fpimm64", AArch64.fpimm64Operand)
        , ("Logical_shifted_reg32", AArch64.gPR32Operand)
        , ("Logical_shifted_reg64", AArch64.gPR64Operand)
        , ("Arith_shifted_reg32", AArch64.gPR32Operand)
        , ("Arith_shifted_reg64", AArch64.gPR64Operand)
        ]

    aarch64Filter = hasNamedString "Namespace" "AArch64" &&&
                    (not . isPseudo) &&&
                    (not . ignoredDef) &&&
                    (not . ignoredMetadata)

    aarch64Pseudo = idPseudo

    pseudoInstructionNames =
        [
        ]

    ignoredDef d = defName d `elem`
        [
        ]

    ignoredMetadataNames = S.fromList $ Metadata <$>
        [
        ]

    ignoredMetadata d = any badMetadata (defMetadata d)
    badMetadata (Metadata m) =
        or [ "SIMD" `L.isInfixOf` m
           , "v" `L.isPrefixOf` m
           , "Vector" `L.isInfixOf` m
           ]

    overrides =
        [ ("ADDHNv2i64_v4i32", FormOverride [("dst", Ignore)])
        , ("ADDHNv4i32_v8i16", FormOverride [("dst", Ignore)])
        , ("ADDHNv8i16_v16i8", FormOverride [("dst", Ignore)])
        , ("ADDSWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ADDSWrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("ADDSXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ADDSXrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("ADDWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ADDWrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("ADDXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ADDXrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("AESDrr", FormOverride [("dst", Ignore)])
        , ("AESErr", FormOverride [("dst", Ignore)])
        , ("ANDSWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ANDSXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ANDWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ANDXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("BFMWri", FormOverride [("src", Ignore)])
        , ("BFMXri", FormOverride [("src", Ignore)])
        , ("BICSWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("BICSXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("BICWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("BICXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("BICv2i32", FormOverride [("dst", Ignore)])
        , ("BICv4i16", FormOverride [("dst", Ignore)])
        , ("BICv4i32", FormOverride [("dst", Ignore)])
        , ("BICv8i16", FormOverride [("dst", Ignore)])
        , ("BITv16i8", FormOverride [("dst", Ignore)])
        , ("BITv8i8", FormOverride [("dst", Ignore)])
        , ("BSLv16i8", FormOverride [("dst", Ignore)])
        , ("BSLv8i8", FormOverride [("dst", Ignore)])
        , ("CASALb", FormOverride [("out", Ignore)])
        , ("CASALd", FormOverride [("out", Ignore)])
        , ("CASALh", FormOverride [("out", Ignore)])
        , ("CASALs", FormOverride [("out", Ignore)])
        , ("CASAb", FormOverride [("out", Ignore)])
        , ("CASAd", FormOverride [("out", Ignore)])
        , ("CASAh", FormOverride [("out", Ignore)])
        , ("CASAs", FormOverride [("out", Ignore)])
        , ("CASLb", FormOverride [("out", Ignore)])
        , ("CASLd", FormOverride [("out", Ignore)])
        , ("CASLh", FormOverride [("out", Ignore)])
        , ("CASLs", FormOverride [("out", Ignore)])
        , ("CASPALd", FormOverride [("out", Ignore)])
        , ("CASPALs", FormOverride [("out", Ignore)])
        , ("CASPAd", FormOverride [("out", Ignore)])
        , ("CASPAs", FormOverride [("out", Ignore)])
        , ("CASPLd", FormOverride [("out", Ignore)])
        , ("CASPLs", FormOverride [("out", Ignore)])
        , ("CASPd", FormOverride [("out", Ignore)])
        , ("CASPs", FormOverride [("out", Ignore)])
        , ("CASb", FormOverride [("out", Ignore)])
        , ("CASd", FormOverride [("out", Ignore)])
        , ("CASh", FormOverride [("out", Ignore)])
        , ("CASs", FormOverride [("out", Ignore)])
        , ("EONWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("EONXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("EORWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("EORXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("FCVTNv4i32", FormOverride [("dst", Ignore)])
        , ("FCVTNv8i16", FormOverride [("dst", Ignore)])
        , ("FCVTXNv4f32", FormOverride [("dst", Ignore)])
        , ("FMLAv1i16_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv1i32_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv1i64_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv2f32", FormOverride [("dst", Ignore)])
        , ("FMLAv2f64", FormOverride [("dst", Ignore)])
        , ("FMLAv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv2i64_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv4f16", FormOverride [("dst", Ignore)])
        , ("FMLAv4f32", FormOverride [("dst", Ignore)])
        , ("FMLAv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("FMLAv8f16", FormOverride [("dst", Ignore)])
        , ("FMLAv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv1i16_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv1i32_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv1i64_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv2f32", FormOverride [("dst", Ignore)])
        , ("FMLSv2f64", FormOverride [("dst", Ignore)])
        , ("FMLSv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv2i64_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv4f16", FormOverride [("dst", Ignore)])
        , ("FMLSv4f32", FormOverride [("dst", Ignore)])
        , ("FMLSv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("FMLSv8f16", FormOverride [("dst", Ignore)])
        , ("FMLSv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("FMOVDXHighr", FormOverride [("idx", Ignore)])
        , ("FMOVXDHighr", FormOverride [("idx", Ignore)])
        , ("INSvi16gpr", FormOverride [("dst", Ignore)])
        , ("INSvi16lane", FormOverride [("dst", Ignore)])
        , ("INSvi32gpr", FormOverride [("dst", Ignore)])
        , ("INSvi32lane", FormOverride [("dst", Ignore)])
        , ("INSvi64gpr", FormOverride [("dst", Ignore)])
        , ("INSvi64lane", FormOverride [("dst", Ignore)])
        , ("INSvi8gpr", FormOverride [("dst", Ignore)])
        , ("INSvi8lane", FormOverride [("dst", Ignore)])
        , ("LD1Fourv16b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv1d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv2d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv2s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv4h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv4s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv8b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Fourv8h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev16b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev1d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev2d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev2s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev4h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev4s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev8b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Onev8h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv16b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv1d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv2d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv2s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv4h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv4s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv8b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Rv8h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev16b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev1d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev2d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev2s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev4h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev4s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev8b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Threev8h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov16b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov1d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov2d_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov2s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov4h_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov4s_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov8b_POST", FormOverride [("wback", Ignore)])
        , ("LD1Twov8h_POST", FormOverride [("wback", Ignore)])
        , ("LD1i16", FormOverride [("dst", Ignore)])
        , ("LD1i16_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD1i32", FormOverride [("dst", Ignore)])
        , ("LD1i32_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD1i64", FormOverride [("dst", Ignore)])
        , ("LD1i64_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD1i8", FormOverride [("dst", Ignore)])
        , ("LD1i8_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD2Rv16b_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv1d_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv2d_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv2s_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv4h_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv4s_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv8b_POST", FormOverride [("wback", Ignore)])
        , ("LD2Rv8h_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov16b_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov2d_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov2s_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov4h_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov4s_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov8b_POST", FormOverride [("wback", Ignore)])
        , ("LD2Twov8h_POST", FormOverride [("wback", Ignore)])
        , ("LD2i16", FormOverride [("dst", Ignore)])
        , ("LD2i16_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD2i32", FormOverride [("dst", Ignore)])
        , ("LD2i32_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD2i64", FormOverride [("dst", Ignore)])
        , ("LD2i64_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD2i8", FormOverride [("dst", Ignore)])
        , ("LD2i8_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD3Rv16b_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv1d_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv2d_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv2s_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv4h_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv4s_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv8b_POST", FormOverride [("wback", Ignore)])
        , ("LD3Rv8h_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev16b_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev2d_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev2s_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev4h_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev4s_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev8b_POST", FormOverride [("wback", Ignore)])
        , ("LD3Threev8h_POST", FormOverride [("wback", Ignore)])
        , ("LD3i16", FormOverride [("dst", Ignore)])
        , ("LD3i16_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD3i32", FormOverride [("dst", Ignore)])
        , ("LD3i32_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD3i64", FormOverride [("dst", Ignore)])
        , ("LD3i64_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD3i8", FormOverride [("dst", Ignore)])
        , ("LD3i8_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD4Fourv16b_POST", FormOverride [("wback", Ignore)])
        , ("LD4Fourv2d_POST", FormOverride [("wback", Ignore)])
        , ("LD4Fourv2s_POST", FormOverride [("wback", Ignore)])
        , ("LD4Fourv4h_POST", FormOverride [("wback", Ignore)])
        , ("LD4Fourv4s_POST", FormOverride [("wback", Ignore)])
        , ("LD4Fourv8b_POST", FormOverride [("wback", Ignore)])
        , ("LD4Fourv8h_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv16b_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv1d_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv2d_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv2s_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv4h_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv4s_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv8b_POST", FormOverride [("wback", Ignore)])
        , ("LD4Rv8h_POST", FormOverride [("wback", Ignore)])
        , ("LD4i16", FormOverride [("dst", Ignore)])
        , ("LD4i16_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD4i32", FormOverride [("dst", Ignore)])
        , ("LD4i32_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD4i64", FormOverride [("dst", Ignore)])
        , ("LD4i64_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LD4i8", FormOverride [("dst", Ignore)])
        , ("LD4i8_POST", FormOverride [("dst", Ignore), ("wback", Ignore)])
        , ("LDPDpost", FormOverride [("wback", Ignore)])
        , ("LDPDpre", FormOverride [("wback", Ignore)])
        , ("LDPQpost", FormOverride [("wback", Ignore)])
        , ("LDPQpre", FormOverride [("wback", Ignore)])
        , ("LDPSWpost", FormOverride [("wback", Ignore)])
        , ("LDPSWpre", FormOverride [("wback", Ignore)])
        , ("LDPSpost", FormOverride [("wback", Ignore)])
        , ("LDPSpre", FormOverride [("wback", Ignore)])
        , ("LDPWpost", FormOverride [("wback", Ignore)])
        , ("LDPWpre", FormOverride [("wback", Ignore)])
        , ("LDPXpost", FormOverride [("wback", Ignore)])
        , ("LDPXpre", FormOverride [("wback", Ignore)])
        , ("LDRBBpost", FormOverride [("wback", Ignore)])
        , ("LDRBBpre", FormOverride [("wback", Ignore)])
        , ("LDRBpost", FormOverride [("wback", Ignore)])
        , ("LDRBpre", FormOverride [("wback", Ignore)])
        , ("LDRDpost", FormOverride [("wback", Ignore)])
        , ("LDRDpre", FormOverride [("wback", Ignore)])
        , ("LDRHHpost", FormOverride [("wback", Ignore)])
        , ("LDRHHpre", FormOverride [("wback", Ignore)])
        , ("LDRHpost", FormOverride [("wback", Ignore)])
        , ("LDRHpre", FormOverride [("wback", Ignore)])
        , ("LDRQpost", FormOverride [("wback", Ignore)])
        , ("LDRQpre", FormOverride [("wback", Ignore)])
        , ("LDRSBWpost", FormOverride [("wback", Ignore)])
        , ("LDRSBWpre", FormOverride [("wback", Ignore)])
        , ("LDRSBXpost", FormOverride [("wback", Ignore)])
        , ("LDRSBXpre", FormOverride [("wback", Ignore)])
        , ("LDRSHWpost", FormOverride [("wback", Ignore)])
        , ("LDRSHWpre", FormOverride [("wback", Ignore)])
        , ("LDRSHXpost", FormOverride [("wback", Ignore)])
        , ("LDRSHXpre", FormOverride [("wback", Ignore)])
        , ("LDRSWpost", FormOverride [("wback", Ignore)])
        , ("LDRSWpre", FormOverride [("wback", Ignore)])
        , ("LDRSpost", FormOverride [("wback", Ignore)])
        , ("LDRSpre", FormOverride [("wback", Ignore)])
        , ("LDRWpost", FormOverride [("wback", Ignore)])
        , ("LDRWpre", FormOverride [("wback", Ignore)])
        , ("LDRXpost", FormOverride [("wback", Ignore)])
        , ("LDRXpre", FormOverride [("wback", Ignore)])
        , ("MLAv16i8", FormOverride [("dst", Ignore)])
        , ("MLAv2i32", FormOverride [("dst", Ignore)])
        , ("MLAv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("MLAv4i16", FormOverride [("dst", Ignore)])
        , ("MLAv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("MLAv4i32", FormOverride [("dst", Ignore)])
        , ("MLAv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("MLAv8i16", FormOverride [("dst", Ignore)])
        , ("MLAv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("MLAv8i8", FormOverride [("dst", Ignore)])
        , ("MLSv16i8", FormOverride [("dst", Ignore)])
        , ("MLSv2i32", FormOverride [("dst", Ignore)])
        , ("MLSv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("MLSv4i16", FormOverride [("dst", Ignore)])
        , ("MLSv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("MLSv4i32", FormOverride [("dst", Ignore)])
        , ("MLSv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("MLSv8i16", FormOverride [("dst", Ignore)])
        , ("MLSv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("MLSv8i8", FormOverride [("dst", Ignore)])
        , ("MOVKWi", FormOverride [("src", Ignore)])
        , ("MOVKXi", FormOverride [("src", Ignore)])
        , ("ORNWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ORNXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ORRWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ORRXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("ORRv2i32", FormOverride [("dst", Ignore)])
        , ("ORRv4i16", FormOverride [("dst", Ignore)])
        , ("ORRv4i32", FormOverride [("dst", Ignore)])
        , ("ORRv8i16", FormOverride [("dst", Ignore)])
        , ("RADDHNv2i64_v4i32", FormOverride [("dst", Ignore)])
        , ("RADDHNv4i32_v8i16", FormOverride [("dst", Ignore)])
        , ("RADDHNv8i16_v16i8", FormOverride [("dst", Ignore)])
        , ("RSHRNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("RSHRNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("RSHRNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("RSUBHNv2i64_v4i32", FormOverride [("dst", Ignore)])
        , ("RSUBHNv4i32_v8i16", FormOverride [("dst", Ignore)])
        , ("RSUBHNv8i16_v16i8", FormOverride [("dst", Ignore)])
        , ("SABALv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SABALv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SABALv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SABALv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SABALv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SABALv8i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SABAv16i8", FormOverride [("dst", Ignore)])
        , ("SABAv2i32", FormOverride [("dst", Ignore)])
        , ("SABAv4i16", FormOverride [("dst", Ignore)])
        , ("SABAv4i32", FormOverride [("dst", Ignore)])
        , ("SABAv8i16", FormOverride [("dst", Ignore)])
        , ("SABAv8i8", FormOverride [("dst", Ignore)])
        , ("SADALPv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SADALPv2i32_v1i64", FormOverride [("dst", Ignore)])
        , ("SADALPv4i16_v2i32", FormOverride [("dst", Ignore)])
        , ("SADALPv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SADALPv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SADALPv8i8_v4i16", FormOverride [("dst", Ignore)])
        , ("SHA1Crrr", FormOverride [("dst", Ignore)])
        , ("SHA1Mrrr", FormOverride [("dst", Ignore)])
        , ("SHA1Prrr", FormOverride [("dst", Ignore)])
        , ("SHA1SU0rrr", FormOverride [("dst", Ignore)])
        , ("SHA1SU1rr", FormOverride [("dst", Ignore)])
        , ("SHA256H2rrr", FormOverride [("dst", Ignore)])
        , ("SHA256Hrrr", FormOverride [("dst", Ignore)])
        , ("SHA256SU0rr", FormOverride [("dst", Ignore)])
        , ("SHA256SU1rrr", FormOverride [("dst", Ignore)])
        , ("SHRNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SHRNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SHRNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SLId", FormOverride [("dst", Ignore)])
        , ("SLIv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SLIv2i32_shift", FormOverride [("dst", Ignore)])
        , ("SLIv2i64_shift", FormOverride [("dst", Ignore)])
        , ("SLIv4i16_shift", FormOverride [("dst", Ignore)])
        , ("SLIv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SLIv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SLIv8i8_shift", FormOverride [("dst", Ignore)])
        , ("SMLALv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SMLALv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("SMLALv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SMLALv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("SMLALv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SMLALv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("SMLALv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SMLALv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("SMLALv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SMLALv8i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SMLSLv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SMLSLv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("SMLSLv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SMLSLv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("SMLSLv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SMLSLv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("SMLSLv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SMLSLv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("SMLSLv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SMLSLv8i8_v8i16", FormOverride [("dst", Ignore)])
        , ("SQDMLALi16", FormOverride [("dst", Ignore)])
        , ("SQDMLALi32", FormOverride [("dst", Ignore)])
        , ("SQDMLALv1i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLALv1i64_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLALv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLALv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SQDMLALv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLALv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SQDMLALv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLALv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SQDMLALv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLALv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SQDMLSLi16", FormOverride [("dst", Ignore)])
        , ("SQDMLSLi32", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv1i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv1i64_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQDMLSLv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHi16_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHi32_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv1i16", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv1i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv2i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv4i16", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv4i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv8i16", FormOverride [("dst", Ignore)])
        , ("SQRDMLAHv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHi16_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHi32_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv1i16", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv1i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv2i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv4i16", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv4i32", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv8i16", FormOverride [("dst", Ignore)])
        , ("SQRDMLSHv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("SQRSHRNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SQRSHRNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SQRSHRNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SQRSHRUNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SQRSHRUNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SQRSHRUNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SQSHRNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SQSHRNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SQSHRNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SQSHRUNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SQSHRUNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SQSHRUNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SQXTNv16i8", FormOverride [("dst", Ignore)])
        , ("SQXTNv4i32", FormOverride [("dst", Ignore)])
        , ("SQXTNv8i16", FormOverride [("dst", Ignore)])
        , ("SQXTUNv16i8", FormOverride [("dst", Ignore)])
        , ("SQXTUNv4i32", FormOverride [("dst", Ignore)])
        , ("SQXTUNv8i16", FormOverride [("dst", Ignore)])
        , ("SRId", FormOverride [("dst", Ignore)])
        , ("SRIv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SRIv2i32_shift", FormOverride [("dst", Ignore)])
        , ("SRIv2i64_shift", FormOverride [("dst", Ignore)])
        , ("SRIv4i16_shift", FormOverride [("dst", Ignore)])
        , ("SRIv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SRIv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SRIv8i8_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAd", FormOverride [("dst", Ignore)])
        , ("SRSRAv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAv2i32_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAv2i64_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAv4i16_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SRSRAv8i8_shift", FormOverride [("dst", Ignore)])
        , ("SSRAd", FormOverride [("dst", Ignore)])
        , ("SSRAv16i8_shift", FormOverride [("dst", Ignore)])
        , ("SSRAv2i32_shift", FormOverride [("dst", Ignore)])
        , ("SSRAv2i64_shift", FormOverride [("dst", Ignore)])
        , ("SSRAv4i16_shift", FormOverride [("dst", Ignore)])
        , ("SSRAv4i32_shift", FormOverride [("dst", Ignore)])
        , ("SSRAv8i16_shift", FormOverride [("dst", Ignore)])
        , ("SSRAv8i8_shift", FormOverride [("dst", Ignore)])
        , ("ST1Fourv16b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv1d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv2d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv2s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv4h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv4s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv8b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Fourv8h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev16b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev1d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev2d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev2s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev4h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev4s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev8b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Onev8h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev16b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev1d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev2d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev2s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev4h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev4s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev8b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Threev8h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov16b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov1d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov2d_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov2s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov4h_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov4s_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov8b_POST", FormOverride [("wback", Ignore)])
        , ("ST1Twov8h_POST", FormOverride [("wback", Ignore)])
        , ("ST1i16_POST", FormOverride [("wback", Ignore)])
        , ("ST1i32_POST", FormOverride [("wback", Ignore)])
        , ("ST1i64_POST", FormOverride [("wback", Ignore)])
        , ("ST1i8_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov16b_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov2d_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov2s_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov4h_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov4s_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov8b_POST", FormOverride [("wback", Ignore)])
        , ("ST2Twov8h_POST", FormOverride [("wback", Ignore)])
        , ("ST2i16_POST", FormOverride [("wback", Ignore)])
        , ("ST2i32_POST", FormOverride [("wback", Ignore)])
        , ("ST2i64_POST", FormOverride [("wback", Ignore)])
        , ("ST2i8_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev16b_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev2d_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev2s_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev4h_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev4s_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev8b_POST", FormOverride [("wback", Ignore)])
        , ("ST3Threev8h_POST", FormOverride [("wback", Ignore)])
        , ("ST3i16_POST", FormOverride [("wback", Ignore)])
        , ("ST3i32_POST", FormOverride [("wback", Ignore)])
        , ("ST3i64_POST", FormOverride [("wback", Ignore)])
        , ("ST3i8_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv16b_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv2d_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv2s_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv4h_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv4s_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv8b_POST", FormOverride [("wback", Ignore)])
        , ("ST4Fourv8h_POST", FormOverride [("wback", Ignore)])
        , ("ST4i16_POST", FormOverride [("wback", Ignore)])
        , ("ST4i32_POST", FormOverride [("wback", Ignore)])
        , ("ST4i64_POST", FormOverride [("wback", Ignore)])
        , ("ST4i8_POST", FormOverride [("wback", Ignore)])
        , ("STPDpost", FormOverride [("wback", Ignore)])
        , ("STPDpre", FormOverride [("wback", Ignore)])
        , ("STPQpost", FormOverride [("wback", Ignore)])
        , ("STPQpre", FormOverride [("wback", Ignore)])
        , ("STPSpost", FormOverride [("wback", Ignore)])
        , ("STPSpre", FormOverride [("wback", Ignore)])
        , ("STPWpost", FormOverride [("wback", Ignore)])
        , ("STPWpre", FormOverride [("wback", Ignore)])
        , ("STPXpost", FormOverride [("wback", Ignore)])
        , ("STPXpre", FormOverride [("wback", Ignore)])
        , ("STRBBpost", FormOverride [("wback", Ignore)])
        , ("STRBBpre", FormOverride [("wback", Ignore)])
        , ("STRBpost", FormOverride [("wback", Ignore)])
        , ("STRBpre", FormOverride [("wback", Ignore)])
        , ("STRDpost", FormOverride [("wback", Ignore)])
        , ("STRDpre", FormOverride [("wback", Ignore)])
        , ("STRHHpost", FormOverride [("wback", Ignore)])
        , ("STRHHpre", FormOverride [("wback", Ignore)])
        , ("STRHpost", FormOverride [("wback", Ignore)])
        , ("STRHpre", FormOverride [("wback", Ignore)])
        , ("STRQpost", FormOverride [("wback", Ignore)])
        , ("STRQpre", FormOverride [("wback", Ignore)])
        , ("STRSpost", FormOverride [("wback", Ignore)])
        , ("STRSpre", FormOverride [("wback", Ignore)])
        , ("STRWpost", FormOverride [("wback", Ignore)])
        , ("STRWpre", FormOverride [("wback", Ignore)])
        , ("STRXpost", FormOverride [("wback", Ignore)])
        , ("STRXpre", FormOverride [("wback", Ignore)])
        , ("SUBHNv2i64_v4i32", FormOverride [("dst", Ignore)])
        , ("SUBHNv4i32_v8i16", FormOverride [("dst", Ignore)])
        , ("SUBHNv8i16_v16i8", FormOverride [("dst", Ignore)])
        , ("SUBSWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("SUBSWrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("SUBSXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("SUBSXrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("SUBWrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("SUBWrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("SUBXrs", FormOverride [("Rd", Ignore), ("Rn", Ignore), ("Rm", Ignore)])
        , ("SUBXrx", FormOverride [("R1", Ignore), ("R2", Ignore), ("R3", Ignore)])
        , ("SUQADDv16i8", FormOverride [("dst", Ignore)])
        , ("SUQADDv1i16", FormOverride [("dst", Ignore)])
        , ("SUQADDv1i32", FormOverride [("dst", Ignore)])
        , ("SUQADDv1i64", FormOverride [("dst", Ignore)])
        , ("SUQADDv1i8", FormOverride [("dst", Ignore)])
        , ("SUQADDv2i32", FormOverride [("dst", Ignore)])
        , ("SUQADDv2i64", FormOverride [("dst", Ignore)])
        , ("SUQADDv4i16", FormOverride [("dst", Ignore)])
        , ("SUQADDv4i32", FormOverride [("dst", Ignore)])
        , ("SUQADDv8i16", FormOverride [("dst", Ignore)])
        , ("SUQADDv8i8", FormOverride [("dst", Ignore)])
        , ("TBXv16i8Four", FormOverride [("dst", Ignore)])
        , ("TBXv16i8One", FormOverride [("dst", Ignore)])
        , ("TBXv16i8Three", FormOverride [("dst", Ignore)])
        , ("TBXv16i8Two", FormOverride [("dst", Ignore)])
        , ("TBXv8i8Four", FormOverride [("dst", Ignore)])
        , ("TBXv8i8One", FormOverride [("dst", Ignore)])
        , ("TBXv8i8Three", FormOverride [("dst", Ignore)])
        , ("TBXv8i8Two", FormOverride [("dst", Ignore)])
        , ("UABALv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UABALv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UABALv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UABALv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UABALv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UABALv8i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UABAv16i8", FormOverride [("dst", Ignore)])
        , ("UABAv2i32", FormOverride [("dst", Ignore)])
        , ("UABAv4i16", FormOverride [("dst", Ignore)])
        , ("UABAv4i32", FormOverride [("dst", Ignore)])
        , ("UABAv8i16", FormOverride [("dst", Ignore)])
        , ("UABAv8i8", FormOverride [("dst", Ignore)])
        , ("UADALPv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UADALPv2i32_v1i64", FormOverride [("dst", Ignore)])
        , ("UADALPv4i16_v2i32", FormOverride [("dst", Ignore)])
        , ("UADALPv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UADALPv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UADALPv8i8_v4i16", FormOverride [("dst", Ignore)])
        , ("UMLALv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UMLALv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("UMLALv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UMLALv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("UMLALv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UMLALv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("UMLALv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UMLALv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("UMLALv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UMLALv8i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UMLSLv16i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UMLSLv2i32_indexed", FormOverride [("dst", Ignore)])
        , ("UMLSLv2i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UMLSLv4i16_indexed", FormOverride [("dst", Ignore)])
        , ("UMLSLv4i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UMLSLv4i32_indexed", FormOverride [("dst", Ignore)])
        , ("UMLSLv4i32_v2i64", FormOverride [("dst", Ignore)])
        , ("UMLSLv8i16_indexed", FormOverride [("dst", Ignore)])
        , ("UMLSLv8i16_v4i32", FormOverride [("dst", Ignore)])
        , ("UMLSLv8i8_v8i16", FormOverride [("dst", Ignore)])
        , ("UQRSHRNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("UQRSHRNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("UQRSHRNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("UQSHRNv16i8_shift", FormOverride [("dst", Ignore)])
        , ("UQSHRNv4i32_shift", FormOverride [("dst", Ignore)])
        , ("UQSHRNv8i16_shift", FormOverride [("dst", Ignore)])
        , ("UQXTNv16i8", FormOverride [("dst", Ignore)])
        , ("UQXTNv4i32", FormOverride [("dst", Ignore)])
        , ("UQXTNv8i16", FormOverride [("dst", Ignore)])
        , ("URSRAd", FormOverride [("dst", Ignore)])
        , ("URSRAv16i8_shift", FormOverride [("dst", Ignore)])
        , ("URSRAv2i32_shift", FormOverride [("dst", Ignore)])
        , ("URSRAv2i64_shift", FormOverride [("dst", Ignore)])
        , ("URSRAv4i16_shift", FormOverride [("dst", Ignore)])
        , ("URSRAv4i32_shift", FormOverride [("dst", Ignore)])
        , ("URSRAv8i16_shift", FormOverride [("dst", Ignore)])
        , ("URSRAv8i8_shift", FormOverride [("dst", Ignore)])
        , ("USQADDv16i8", FormOverride [("dst", Ignore)])
        , ("USQADDv1i16", FormOverride [("dst", Ignore)])
        , ("USQADDv1i32", FormOverride [("dst", Ignore)])
        , ("USQADDv1i64", FormOverride [("dst", Ignore)])
        , ("USQADDv1i8", FormOverride [("dst", Ignore)])
        , ("USQADDv2i32", FormOverride [("dst", Ignore)])
        , ("USQADDv2i64", FormOverride [("dst", Ignore)])
        , ("USQADDv4i16", FormOverride [("dst", Ignore)])
        , ("USQADDv4i32", FormOverride [("dst", Ignore)])
        , ("USQADDv8i16", FormOverride [("dst", Ignore)])
        , ("USQADDv8i8", FormOverride [("dst", Ignore)])
        , ("USRAd", FormOverride [("dst", Ignore)])
        , ("USRAv16i8_shift", FormOverride [("dst", Ignore)])
        , ("USRAv2i32_shift", FormOverride [("dst", Ignore)])
        , ("USRAv2i64_shift", FormOverride [("dst", Ignore)])
        , ("USRAv4i16_shift", FormOverride [("dst", Ignore)])
        , ("USRAv4i32_shift", FormOverride [("dst", Ignore)])
        , ("USRAv8i16_shift", FormOverride [("dst", Ignore)])
        , ("USRAv8i8_shift", FormOverride [("dst", Ignore)])
        , ("XTNv16i8", FormOverride [("dst", Ignore)])
        , ("XTNv4i32", FormOverride [("dst", Ignore)])
        , ("XTNv8i16", FormOverride [("dst", Ignore)])
        ]
