# This CI configuration is inspired by
#
# https://kodimensional.dev/github-actions
#
# It builds with a majority of the latest compiler releases from each major GHC
# revision on Linux and builds macOS and Windows against the latest GHC.
name: CI Matrix

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: ['tablegen', 'arm', 'thumb', 'ppc', 'aarch64', 'arm-xml']
        ghc: ['8.10.7', '9.2.7', '9.4.4']
        cabal: ['3.8.1.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          # Only test macOS and Windows on the latest supported GHC versions
          - os: macOS-latest
            ghc: 8.10.7
          - os: macOS-latest
            ghc: 9.2.7
          - os: windows-latest
            ghc: 8.10.7
          - os: windows-latest
            ghc: 9.2.7
          # This configuration runs out of memory
          - os: windows-latest
            arch: aarch64

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }} dismantle-${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cp cabal.project.newbuild cabal.project
        cabal v2-configure pkg:dismantle-${{ matrix.arch }} --write-ghc-environment-files=always -j1
        cabal v2-build pkg:dismantle-${{ matrix.arch }}

    - name: Test
      if: runner.os == 'Linux'
      run: |
        cabal v2-test pkg:dismantle-${{ matrix.arch }}
