name: CI Matrix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }} dismantle-${{ matrix.pkg }}
    strategy:
      matrix:
        ghc: ['9.6.7', '9.8.4', '9.10.1']
        cabal: ['3.14.2.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        pkg: ['tablegen', 'arm', 'thumb', 'ppc', 'aarch64', 'arm-xml']
        exclude:
          # Only test macOS and Windows on the latest supported GHC versions
          - os: macOS-latest
            ghc: 9.6.7
          - os: macOS-latest
            ghc: 9.8.4
          - os: windows-latest
            ghc: 9.6.7
          - os: windows-latest
            ghc: 9.8.4
          # This configuration runs out of memory
          - os: windows-latest
            pkg: aarch64
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1
    with:
      build-targets: dismantle-${{ matrix.pkg }}
      check: false
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
      pre-hook: |
        cp cabal.project.newbuild cabal.project
      sdist-targets: dismantle-${{ matrix.pkg }}
      submodules: "true"
      test-targets: dismantle-${{ matrix.pkg }}
      test: ${{ startsWith(matrix.os, 'ubuntu') }}
